### ISSUE TITLE
Non Uniform Register Widths

### ISSUE THREAD

**Issue by mkahane** [SystemRDL/PeakRDL-regblock#12]
I was wondering if there is a plan to implement strobe signals to support non-uniform register widths.  It seems from this line that it is likely on the roadmap, but I'm curious if it is likely to be sooner or later 
https://github.com/SystemRDL/PeakRDL-regblock/blob/main/src/peakrdl_regblock/scan_design.py#L82

**Comment by amykyta3** [comment]
Yeah its definitely on my roadmap to add support for strobes. Currently for axi4-lite I outright ignore WSTRB, and I'd love to be able to have proper APB4 support which includes PSTRB.
As you have implied, this also has a close relationship with how support for non-uniform register widths works. I have plans to expand the code generator to handle that too but there are a handful of freaky edge cases that arise with both of those that I need to still work out. (for example its possible to read/write multiple registers in one go. Or, what happens if you access only half of a register, etc...)
Regarding timeline, I've put this project on a short break to focus on other stuff, but I imagine I'll pick it back up in the fall once the good summer weather ends. It is my bizarre hobby project after all...

**Comment by amykyta3** [comment]
Welp... looks like the nice summer weather ended but not in the way I had anticipated. I had some time to muck around with this.

Support for PSTRB was added a few weeks ago in v0.7.0.

Initial support for non-uniform regwidths has been added in v0.8.0, but still has some limitations. Namely, there are some [restrictions on accesswidth](https://peakrdl-regblock.readthedocs.io/en/latest/limitations.html#uniform-accesswidth) that are pretty low priority in my opinion.

For 'wide' registers (where regwidth > accesswidth), there is still pretty limited utility since one implicitly cannot access them atomically (think 64-bit counter with 32-bit accesswidth). For some reason the standard does not define this. To solve that, I have plans to extend SystemRDL properties via UDPs to allow designers to enable double-buffering on these registers.
