### ISSUE TITLE
swmod latency 

### ISSUE THREAD

**Issue by proukema-fidus** [SystemRDL/PeakRDL-regblock#19]
Currently the swmod signal on a register is asserted before the update output data is available. This requires it be delayed externally by one lock in order to use it as a write enable to a FIFO/RAM/etc. It would seem to make more sense to delay it one clock so it aligned with the value update. Is the current behavior required by the SystemRDL spec or implementation defined? Obviously there may be some issue with updating it now, as it would be a (silent) breaking change. It could be an option, but that seems excessive?

One potential downside would be that swacc and swmod could be triggered in different clock cycles for the same access.

![image](https://user-images.githubusercontent.com/28118384/191322879-d5496802-9a57-444c-be5a-9e8fb2596e1b.png)

**Comment by amykyta3** [comment]
The spec doesn't explicitly define the behavior one way or the other. In
the case of the regblock generator, this was an intentional decision I had
made. There are several situations where one would want to know whether a
field is *about to be *modified, especially when using the swmod referenced
in the righthand side of an RDL assignment. Advancing this signal to assert
1 cycle early gives you the flexibility of both behaviors if needed. Also
as you point out, it results in better symmetry with swacc.

Another way to phrase the behavior that may make it more palatable:

   - swacc = field is *currently being read *by software
   - swmod= field is *currently being written *by software
