### ISSUE TITLE
Add override for all resets to be asynchronous by default

### ISSUE THREAD

**Issue by galaviel** [SystemRDL/PeakRDL-regblock#34]
PeakRDL seems to emit synchronous reset currently.
Add the option (via cmdline, config file, etc.) to emit Async reset.
Out standard cell libraries uses ASYNC reset for all FF's.

**Comment by galaviel** [comment]
Also consider: Reset Polarity.
Currently regblock seems to default to "active high" however I believe most ASIC designs use "active low".
Simple textual search & replace can be used to work-around that; however would be nice to have the toolchain emit suitable polarity in the first place.

**Comment by amykyta3** [comment]
Once internal to an ASIC (or FPGA), active high vs active low becomes a matter of preference and generally doesn't matter with most technology nodes I have worked with.
That said, I recognize that organizations will have differing conventions, so this seems like a sensible thing to add.

I'll be sure to add this as a command-line flag as well as a `peakrdl.toml` configuration option, since both could be useful.

In the meantime, be aware that you can already control this using a `cpuif_reset` signal declaration in the top `addrmap`:
```
addrmap top {
    signal {
        cpuif_reset;
        async;
        activelow;
    } rst_n;
};

**Comment by galaviel** [comment]
thanks! that sounds great.

Regarding reset, the above RDL code snippet only seems to reset the CPU I/F.

The storage seems to remains reset by 'rst' (active high, sync).

So the feature of controlling the storage's reset is still valuable..
also it's desirable IMHO to be able to separate the access logic from the storage reset.
Sometimes you want to perform 'logic' reset to a unit (including all the bus elements) but retain the configuration (storage) so as to save SW from needing to re-configure the block.

**Comment by amykyta3** [comment]
Ah I forgot to add the `field_reset` property too:
```
signal {
    cpuif_reset;
    field_reset;
    async;
    activelow;
} arst_n;
```

But either way, agree this would be a useful thing to add. This will be up next after I finish #4

**Comment by galaviel** [comment]
sounds great! trying... (simulation still running..)
but looks good.

**Comment by amykyta3** [comment]
Implemented this feature. Will be in the next release.

**Comment by galaviel** [comment]
Awsome !! thank you!
