### ISSUE TITLE
Thoughts on address decoder implementation

### ISSUE THREAD

**Issue by jeras** [SystemRDL/PeakRDL-regblock#66]
I did not look into the SystemVerilog sources much yet, so this is based on the documentation.

### Full duplex read/write

Protocols like AMBA AXI3/4/5 (full and lite) support simultaneous read and write access to registers, while protocols like APB, Wishbone and AHB (not sure) do not. I am also not sure about TileLink, I might check later.

Implementing a single decoder for both read and write prevents simultaneous access and thus limits throughput.

I would propose for this to be a parameterizable between full and half duplex (shared/common and independent channels in AMBA AXI words).

### 1-hot versus binary address decoder

It is commonly thought that 1-hot encoding is in general superior to binary.

In practice this is not always true, I will give as an example a peripheral with 4 registers focusing on the read path.

On FPGAs with a 6 input LUT (Xilinx 7 family) a single LUT6 can be used to multiplex the 4 register values into one read data output. The register bit values take 4 of the LUT6 inputs while the address takes 2 of the LUT6 inputs.

If you compare this to an 1-hot solution, now the select signal in 4-bits and with 4 data bits, it will not fit into LUT6 so a logic cell hierarchy would be created.

While I did not check it properly I also think FPGA/ASIC tool vendors have spent significant efforts into optimizing address decoders written as case statements with a binary select, since this is the most common coding style.

In relation to the shared/independent read/write address decoder, I also think FPGA synthesis might not consume more logic resources with binary independent decoders.

### internal bus handshake signals req/ack versus the standard valid/ready

I would like to see the AXI valid/ready handshake used in the internal bus instead of the req/ack pair.
The standard AXI valid/ready handshake is almost universally understood, so there is usually no need to document it in detail.
While with req/ack the user might assume something wrong.

There is also a performance/throughput bottleneck in the cpuif_req/spuif_rd_ack handshake for read access. The acknowledge signal is active when read data is valid. If read data is delayed due to re-timing stages, this will prevent back to back read accesses.

To prevent this throughput issue, the handshake should refer only to the address decoder, while read data is always available a fixed delay after the address transfer. So with AXI the RA channel (read address) could receive ready in the same cycle as the valid (so the manager could issue a new read request), and after a fixed delay the AXI R (read data) valid signal would be driven high by the peripheral to indicate read data is available.

I am working on a system bus with this feature, I will just link to a [waveform](https://github.com/jeras/TCB/blob/main/doc/TCB.md#read-transfer).

**Comment by amykyta3** [comment]
Thank you for your thoughts.

Although true that full duplex could offer more throughput for a register block architecture, I intentionally chose not to design this generator to support it since it offers some simplifications to the design as it implicitly avoids read/write collisions. Also, i would argue that concurrent read/writes for a CSR block that is accessed by software is rarely necessary as these are accessed by software that manipulates a peripheral.

Regarding decoding, even a binary address decoder implemented as a large case-statement will ultimately distill down to 1-hot strobes that control FF's CE signal. I would expect that explicitly breaking apart the operation into comparitors would make little difference, and still allow for the very common optimization of logic merging (or LUT combining in FPGAs).

Lastly for handshake signals, this is intentional to allow for better decoupling of internal components. Ready/valid handshakes are excellent in situations where there is handshaking between point-to-point connections, but not particularly appropriate in the internals of a regblock where there is large fanout/fanin across potentially thousands of registers. You'll also find that the handshake I define does indeed allow for back-to-back operations even with retiming stages enabled. It does not require each req/ack to be resolved before proceeding to the next. It can be pipelined as described here: https://peakrdl-regblock.readthedocs.io/en/latest/cpuif/internal_protocol.html#transaction-pipelining-stalls
